# Generated by Django 5.1.7 on 2025-03-25 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empid', models.CharField(max_length=10)),
                ('ename', models.CharField(max_length=30)),
                ('desg', models.CharField(max_length=15)),
            ],
        ),
    ]
